In [1]:
#export
from torch import tensor
import torch
def matmul(a,b):
    return torch.einsum("ik,kj->ij",a,b) # mat mul with einsum

In [2]:
def matmul_old(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    ans = torch.zeros(ar,bc)
    for i in range(bc):
        ans[...,i] = (a * b[:,i]).sum(1)
    return ans

## Testing

In [3]:
m3 = tensor([[1,2,3],
           [2,3,4]])
m4 = tensor([[1,3],
            [4,-2],
            [0,-1]])

In [4]:
import time
%time m3@m4

CPU times: user 317 µs, sys: 50 µs, total: 367 µs
Wall time: 214 µs


tensor([[ 9, -4],
        [14, -4]])

In [5]:
%time matmul(m3,m4)

CPU times: user 0 ns, sys: 5.74 ms, total: 5.74 ms
Wall time: 1.77 ms


tensor([[ 9, -4],
        [14, -4]])

**@ method is three times faster than einsum**

In [6]:
%time matmul_old(m3,m4)

CPU times: user 4.9 ms, sys: 0 ns, total: 4.9 ms
Wall time: 22.1 ms


tensor([[ 9., -4.],
        [14., -4.]])

*old matmul is much much slower than the einsum. Einsum is the fastest non blas method to do mat mul*

In [7]:
! python notebook2script.py matmul.ipynb

Converted matmul.ipynb to utils/matmul.py
